# Generated by Django 3.0.6 on 2020-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'org',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.CharField(default='c4f2a676-1ca1-4921-950a-1ad8cc6bda36', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('empno', models.BigIntegerField(db_index=True)),
                ('group', models.ManyToManyField(to='api.Organization')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
