# Generated by Django 3.0.6 on 2020-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(1, '开发'), (2, '运维'), (3, '产品'), (4, '测试')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.CharField(default='f845bf11-a134-4d5e-a20a-00f5c9debab1', max_length=36, primary_key=True, serialize=False),
        ),
    ]
